"""Component D of the "PROVEN != meaningful" work (Gate C3/C6, source-fidelity
vector): the source-anchored, blind, logged Gate C6 review.

The original Gate C6 (`evidence/dafny_nl_summary.py`) asks a human to confirm
a spec matches a plain-English *summary the same system generated from the
spec*. That is a rubber stamp: drafter and checker are the same kind of
system, so the checker inherits the drafter's blind spots (the very principle
`evidence/citation_gate.py` already articulates for citations). This component
reforms the review into one that is:

  - **source-anchored** - each numeric constant is shown next to the verbatim
    SOURCE quote it must transcribe (reused from Component C's
    `literal_citations.yaml`, already CONFIRMED present in the source), not a
    self-generated summary;
  - **blind** - the reviewer writes the value/boundary they expect FROM THE
    SOURCE before the spec's actual constant is revealed (kept in a collapsed
    block), so agreement means the source and spec independently point to the
    same number, not that the reviewer read the spec's answer and nodded;
  - **logged** - reviewer name, date, and an explicit drafter != checker
    attestation are recorded.

This module only builds the template and mechanically checks its *structure*
(every source constant present with a CONFIRMED quote, every required field
present). It deliberately does NOT perform the review: the sign-off is a human
act, and having the drafting system fill it would recreate the rubber stamp
this component exists to remove. A freshly generated template is therefore
PENDING - structurally valid but not yet reviewed - and the structure gate
passes on a PENDING template. Whether a *completed* review exists is a separate
signal (`review_complete`), reported but not asserted by the structure gate.
"""

import pathlib

import yaml

from evidence.citation_gate import CitationClaim, verify_citation

PENDING = "_PENDING_"

# The fields a well-formed review carries. The structure gate checks each
# marker is present; it does NOT check they've been filled (that is
# review_complete, a human act left out-of-band).
_HEADER_FIELDS = ("Reviewer:", "Date:", "Attestation", "Status:")
_PER_CONSTANT_FIELDS = ("Source says", "Blind expectation", "Spec uses", "Captures the source")

_ATTESTATION = (
    "I am a human reviewer, and not the system that drafted this spec "
    "(drafter != checker)."
)


def load_manifest(manifest_path):
    return yaml.safe_load(pathlib.Path(manifest_path).read_text(encoding="utf-8"))["literals"]


def _source_constants(manifest):
    """The source-cited constants, in manifest order: [(literal, entry)]."""
    return [(lit, e) for lit, e in manifest.items() if e.get("kind") == "source"]


def build_review(spec_name, manifest):
    """Render a PENDING source-anchored blind-review template for `spec_name`
    (e.g. 'renal_adjustment.dfy') from its citation `manifest`. One review
    block per source-cited numeric constant; structural/design_decision
    constants are listed as declared (no source to blind-check)."""
    lines = [
        f"# Source-anchored Gate C6 review — `{spec_name}`",
        "",
        "Generated by `evidence/source_anchored_review.py`. This is the "
        "source-anchored, blind reform of Gate C6 (Component D): each numeric "
        "constant is checked against the verbatim source it transcribes, and "
        "the reviewer records what the source implies BEFORE the spec's answer "
        "is revealed. See the module docstring for why drafter != checker.",
        "",
        "## Sign-off",
        "",
        f"- Reviewer: {PENDING}",
        f"- Date: {PENDING}",
        f"- Attestation (drafter != checker): {PENDING} — \"{_ATTESTATION}\"",
        f"- Status: {PENDING} (a freshly generated template is PENDING — "
        "structurally valid, not yet reviewed)",
        "",
        "## How to complete this review",
        "",
        "For each constant below: read the **Source says** quote, write in "
        "**Blind expectation** the value or boundary you expect the spec to "
        "use *from the source alone*, THEN expand **Spec uses** and record in "
        "**Captures the source** whether they agree. Fill the sign-off above "
        "and replace every `_PENDING_`.",
        "",
        "## Source-anchored constants",
        "",
    ]
    for i, (lit, entry) in enumerate(_source_constants(manifest), 1):
        lines += [
            f"### {i}. `{entry['source']}`",
            "",
            "**Source says (verbatim):**",
            "",
            f"> {entry['quote']}",
            "",
            f"**Blind expectation** (fill from the source above, before "
            f"revealing the spec's value): {PENDING}",
            "",
            "<details><summary><b>Spec uses</b> (reveal only after filling the "
            "blind expectation)</summary>",
            "",
            f"The spec's constant here is `{lit}`.",
            "",
            "</details>",
            "",
            f"**Captures the source?** {PENDING} (yes / no + notes)",
            "",
        ]
    declared = [(lit, e) for lit, e in manifest.items() if e.get("kind") != "source"]
    if declared:
        lines += ["## Declared constants (no source to blind-check)", ""]
        for lit, entry in declared:
            lines.append(f"- `{lit}` — **{entry['kind']}**: {entry['note'].strip()}")
        lines.append("")
    return "\n".join(lines)


def _spec_marker(lit):
    """The per-literal line `build_review` emits inside each constant's block.
    It embeds the literal itself, so it is unique to that block even when two
    constants share the same verbatim source quote (e.g. renal's 89 and 60
    both cite one KDIGO row) - which a bare quote-presence test cannot tell
    apart."""
    return f"The spec's constant here is `{lit}`."


def check_structure(markdown, manifest, source_texts):
    """Mechanically check a review artifact's STRUCTURE (not its human
    verdicts). Returns a report dict:
      - missing_fields:    required field markers absent from the artifact
      - missing_blocks:    source constants whose own review block (its unique
                           per-literal marker) is absent - the per-constant
                           guarantee a shared-quote substring test can't give
      - missing_quotes:    source constants whose verbatim quote isn't shown
      - unconfirmed:       shown source quotes NOT found in their source text
      - structure_ok:      True iff the above are all empty (PENDING is fine)
      - review_complete:   True iff no `_PENDING_` remains (a human filled it)
    A well-formed but unreviewed template is structure_ok=True,
    review_complete=False - which is the expected committed state.

    The per-literal marker check is what stops a specific constant's block
    being deleted and masked by another constant that happens to cite the
    same quote: because two literals never share a marker, dropping one
    block always drops its marker, whatever its quote."""
    missing_fields = [f for f in _HEADER_FIELDS if f not in markdown]
    for f in _PER_CONSTANT_FIELDS:
        if _source_constants(manifest) and f not in markdown:
            missing_fields.append(f)

    missing_blocks = []
    missing_quotes = []
    unconfirmed = []
    for lit, entry in _source_constants(manifest):
        if _spec_marker(lit) not in markdown:
            missing_blocks.append(lit)
        quote = entry["quote"]
        if quote not in markdown:
            missing_quotes.append(lit)
        src = entry["source"]
        text = source_texts.get(src, "")
        verdict = verify_citation(
            CitationClaim(label=f"{lit}@{src}", claimed_quote=quote, source_text=text)
        )
        if verdict.verdict != "CONFIRMED":
            unconfirmed.append(lit)

    return {
        "missing_fields": missing_fields,
        "missing_blocks": missing_blocks,
        "missing_quotes": missing_quotes,
        "unconfirmed": unconfirmed,
        "structure_ok": not (
            missing_fields or missing_blocks or missing_quotes or unconfirmed
        ),
        "review_complete": PENDING not in markdown,
    }


def check_example(review_path, manifest_path, sources_dir):
    """Convenience wrapper: read a committed review artifact and its manifest,
    read the source texts the manifest names (confined to `sources_dir` via
    literal_citation._resolve_within), and structure-check the review."""
    from evidence.literal_citation import _resolve_within

    markdown = pathlib.Path(review_path).read_text(encoding="utf-8")
    manifest = load_manifest(manifest_path)
    source_texts = {}
    for _lit, entry in _source_constants(manifest):
        name = entry["source"]
        if name not in source_texts:
            source_texts[name] = _resolve_within(sources_dir, name).read_text(encoding="utf-8")
    return check_structure(markdown, manifest, source_texts)
