// GENERATED by generate_dosage_differential_driver.py from
// dosage_differential_vectors.py - do not hand-edit. Regenerate:
//   python generate_dosage_differential_driver.py
//
// R5 differential-testing harness (RISK_MANAGEMENT_FINDINGS.md):
// calls the real CalculateHourlyDose (dosage.dfy, included below,
// not reimplemented) once per shared vector and prints its result
// as "id|dose" for run_verify_dosage_differential.py to compare
// against dosage.py's output on the identical inputs.

include "dosage.dfy"

method Main() {
  var ordinary_in_range := CalculateHourlyDose(2.0, 3.0, 10.0);
  print "ordinary_in_range|", ordinary_in_range, "\n";
  var ordinary_negative_rate := CalculateHourlyDose(2.0, -5.0, 10.0);
  print "ordinary_negative_rate|", ordinary_negative_rate, "\n";
  var boundary_rate_zero := CalculateHourlyDose(2.0, 0.0, 10.0);
  print "boundary_rate_zero|", boundary_rate_zero, "\n";
  var boundary_raw_equals_max := CalculateHourlyDose(2.0, 5.0, 10.0);
  print "boundary_raw_equals_max|", boundary_raw_equals_max, "\n";
  var clamp_above_max := CalculateHourlyDose(2.0, 6.0, 10.0);
  print "clamp_above_max|", clamp_above_max, "\n";
  var fractional_exact_below := CalculateHourlyDose(4.0, 1.5, 10.0);
  print "fractional_exact_below|", fractional_exact_below, "\n";
  var fractional_exact_at_boundary := CalculateHourlyDose(4.0, 2.5, 10.0);
  print "fractional_exact_at_boundary|", fractional_exact_at_boundary, "\n";
  var large_but_finite := CalculateHourlyDose(10000000000.0, 10000000000.0, 10.0);
  print "large_but_finite|", large_but_finite, "\n";
  var overflow_negative_mirrors_test_dosage_concrete := CalculateHourlyDose(100000000000000001097906362944045541740492309677311846336810682903157585404911491537163328978494688899061249669721172515611590283743140088328307009198146046031271664502933027185697489699588559043338384466165001178426897626212945177628091195786707458122783970171784415105291802893207873272974885715430223118336.0, -2.0, 10.0);
  print "overflow_negative_mirrors_test_dosage_concrete|", overflow_negative_mirrors_test_dosage_concrete, "\n";
}
