# Phase-A glue script: builds VerificationResult records from the captured
# Sample A fixtures (run_manifest.json + raw_crosshair_output.txt) and runs
# the hand-reviewed renderer to produce traceability_matrix.json/.md.
# This is NOT the Phase-B adapter/binder — it is the minimal, reviewable
# bridge that guarantees the committed matrices are generated by the real
# logic in evidence/render/manual_matrix.py, not hand-typed.
import json
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).parent
REPO_ROOT = HERE.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from evidence.model import Strength, VerificationResult  # noqa: E402
from evidence.render.manual_matrix import build_traceability_matrix  # noqa: E402


def main():
    manifest = json.loads((HERE / "run_manifest.json").read_text())
    raw = (HERE / "raw_crosshair_output.txt").read_text()
    metadata = yaml.safe_load((HERE / "metadata.yaml").read_text())

    if manifest["exit_code"] != 0 or "false" in raw.lower().split():
        sys.exit(
            "Sample A capture does not report a clean pass "
            f"(exit_code={manifest['exit_code']}); refusing to build a matrix "
            "that claims no_counterexample."
        )

    result = VerificationResult(
        method="crosshair",
        code_location="dosage.py::calculate_hourly_dose",
        raw_status="no_counterexample",
        strength=Strength.BOUNDED_CHECKED,
        run_id=manifest["started_utc"],
        timestamp=manifest["started_utc"],
        bounds=metadata["toolchain"]["crosshair_bounds"],
    )
    matrix, markdown = build_traceability_matrix(
        metadata, [result], tool_versions={"crosshair": manifest["tool_version"]}
    )
    (HERE / "traceability_matrix.json").write_text(json.dumps(matrix, indent=2) + "\n")
    (HERE / "traceability_matrix.md").write_text(markdown)
    print("wrote traceability_matrix.json and traceability_matrix.md")


if __name__ == "__main__":
    main()
