"""Generates dosage_differential_driver.dfy from
dosage_differential_vectors.py's shared VECTORS list.

Deliberately generated, not hand-authored, matching this repo's own
"single source of truth" discipline (evidence/test_catalog.py,
evidence/hazard_id_lint.py): the alternative - typing the same test
vectors into a second, independently-maintained .dfy file - is exactly
the kind of duplication that let dosage.py's postcondition drift from
dosage.dfy's undetected for over a week (R5's own finding). The
generated driver `include`s dosage.dfy directly (Dafny's own file-
inclusion mechanism, not a copy of CalculateHourlyDose's logic) and
calls it once per vector, printing "id|dose\n" per line for
run_verify_dosage_differential.py to parse.

Usage:
    python generate_dosage_differential_driver.py

Regenerate whenever dosage_differential_vectors.py changes.
tests/test_dosage_differential.py fails CI if the committed
dosage_differential_driver.dfy drifts from what this generator
produces against the committed vectors - the same "generated artifact
must match its generator" discipline evidence/cli.py's and
evidence/test_catalog.py's own tests already apply elsewhere.
"""

import pathlib

from dosage_differential_vectors import VECTORS

HERE = pathlib.Path(__file__).parent
OUT = HERE / "dosage_differential_driver.dfy"


def render(vectors: list) -> str:
    lines = [
        "// GENERATED by generate_dosage_differential_driver.py from",
        "// dosage_differential_vectors.py - do not hand-edit. Regenerate:",
        "//   python generate_dosage_differential_driver.py",
        "//",
        "// R5 differential-testing harness (RISK_MANAGEMENT_FINDINGS.md):",
        "// calls the real CalculateHourlyDose (dosage.dfy, included below,",
        "// not reimplemented) once per shared vector and prints its result",
        '// as "id|dose" for run_verify_dosage_differential.py to compare',
        "// against dosage.py's output on the identical inputs.",
        "",
        'include "dosage.dfy"',
        "",
        "method Main() {",
    ]
    for vector in vectors:
        concentration = _dafny_real_literal(vector["concentration_mg_per_ml"])
        rate = _dafny_real_literal(vector["infusion_rate_ml_per_hr"])
        max_dose = _dafny_real_literal(vector["max_safe_dose_mg_per_hr"])
        lines.append(
            f"  var {vector['id']} := CalculateHourlyDose({concentration}, {rate}, {max_dose});"
        )
        lines.append(f'  print "{vector["id"]}|", {vector["id"]}, "\\n";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def _dafny_real_literal(value: float) -> str:
    """Dafny real literals need an explicit decimal point (`10` is an
    int literal, `10.0` is a real one) and don't accept Python's `e`
    scientific notation - render every value as a plain decimal
    instead. Values here are all whole numbers or clean fractions
    (dosage_differential_vectors.py's own docstring states this
    scoping choice), so this never needs to render a repeating or
    very-long decimal expansion."""
    if value == int(value) and abs(value) < 1e15:
        return f"{int(value)}.0"
    text = repr(value)
    if "e" in text or "E" in text:
        # 1e10, 1e308 etc. render here too, since abs(value) >= 1e15
        # skips the branch above - but int() on a float is only lossless
        # when the float is already integer-valued (true of every vector
        # committed today: 1e10, 1e308). A *fractional* scientific-notation
        # value (e.g. 1e-5) would silently truncate to 0.0 via int() -
        # refuse rather than guess, matching this repo's own false-zero-
        # guard discipline (evidence/dafny_adapter.py).
        if not value.is_integer():
            raise ValueError(
                f"_dafny_real_literal cannot serialize {value!r}: it is "
                "fractional and would render in scientific notation, but "
                "this function only has a lossless path for integer-valued "
                "scientific-notation floats. Add explicit plain-decimal "
                "handling before using a vector like this."
            )
        return f"{int(value)}.0"
    return text


def main() -> None:
    OUT.write_text(render(VECTORS))


if __name__ == "__main__":
    main()
